sudo: required
services: 
  - docker

before_install: 
  - docker build -t kaiorosa1/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true kaiorosa1/react-test npm test -- --coverage 

after_success: 
  - docker build -t kaiorosa1/multi-client ./client
  - docker build -t kaiorosa1/multi-nginx ./nginx
  - docker build -t kaiorosa1/multi-server ./server
  - docker build -t kaiorosa1/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaiorosa1/multi-client
  - docker push kaiorosa1/multi-nginx
  - docker push kaiorosa1/multi-server
  - docker push kaiorosa1/multi-worker
