sudo: required
services: 
  - docker

before_install: 
  - docker build -e CI=true -t kaiorosa/react-test -f ./client/Dockerfile../client/Dockerfile.dev ./client

script: 
  - docker run kaiorosa/react-test npm test -- --coverage 

after_success: 
  - docker build -t kaiorosa/multi-client ./client
  - docker build -t kaiorosa/multi-nginx ./nginx
  - docker build -t kaiorosa/multi-server ./server
  - docker build -t kaiorosa/multi-worker ./worker